spring:
  cloud:
    zookeeper:
        discovery:
            root: /prod/metawebthree
spring.quartz.jdbc.initialize-schema: never
logging:
  level:
    com.metawebthree: ERROR
    org.springframework.web: ERROR