env-ip: localhost
spring:
  profiles:
    active: dev
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        # root: /meta-web-three
  datasource:
    driver-class-name: org.postgresql.Driver
    # quartz:
    # #如果需要quartz 第一次运行时自动生成 quartz 所需的表那么 quartzJob? 后面的配置为 ：allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    #   url: jdbc:mysql://localhost:3306/quartzJob?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    #   username: admin
    #   password: 123123
  # data:
  #   redis:
  #     host: ${env-ip}
  #     port: 6379
  #     password:
  #     database: 0
  #     timeout: 10000ms
  #     lettuce:
  #       pool:
  #         max-active: 8
  #         max-wait: -1ms
  #         max-idle: 8
  #         min-idle: 0
  quartz:
    job-store-type: JDBC
    auto-startup: true
    startup-delay: 0
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MetaWebThreeScheduler
          jobStore:
            isClustered: true
            instanceId: AUTO
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
name: "meta-web-three"
page-config:
  page-size: 20
aws:
  region: ap-southeast-1
  s3:
    buckets:
      name: metawebthree
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
rocketmq:
  client:
    namesrv: ${env-ip}:9876
    appliaction-topic: "publicApplicationTopic"
jwt:
  secret: mwt123123
dubbo:
  registry:
    protocol: zookeeper
    timeout: 30000
  provider:
    timeout: 10000 # service call timeout
  protocol:
    port: -1
    name: tri
    serialization: protobuf
grpc:
  discovery:
    path-template: /grpc/{spring.application.name}/providers
