services:
  etcd:
    # image: bitnamilegacy/etcd:latest
    image: quay.io/coreos/etcd:v3.6.6
    container_name: default-milvus-etcd
    environment:
      # ALLOW_NONE_AUTHENTICATION: yes
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd-data
    volumes:
      - etcd_data:/etcd-data
    networks:
      - default-ai

  minio:
    image: minio/minio:latest
    container_name: default-milvus-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-123123123}
      # MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
      # MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-123123123}
    ports:
      - "${MINIO_PORT1:-9000}:9000"
      - "${MINIO_PORT2:-9001}:9001"
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - default-ai

  milvus:
    image: milvusdb/milvus:v2.6.5
    container_name: default-milvus
    command: ["milvus", "run", "standalone"]
    ports:
      - "${MILVUS_PORT1:-19530}:19530"
      - "${MILVUS_PORT2:-9091}:9091"
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      # MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
      # MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-123123123}
      # MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-milvus-bucket}
    volumes:
      - milvus_data:/var/lib/milvus
      - ./milvus-config/milvus.yaml:/milvus/configs/milvus.yaml
    depends_on:
      - "etcd"
      - "minio"
    restart: unless-stopped
    networks:
      - default-ai

volumes:
  milvus_data:
  minio_data:
  etcd_data:

networks:
  default-ai:
    driver: bridge