server:
  port: 10087
spring:
  application:
    name: promotion-service
  profiles:
    active: dev
dubbo:
  application:
    name: promotion-service
  protocol:
    port: 20087
promotion:
  coupon:
    retry-limit: 5
    max-generate-count: 1000
    code-length: 10
    code-alphabet: ABCDEFGHJKLMNPQRSTUVWXYZ23456789
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml
